name: extension_dart_tools
description: Tools functions and extensions in dart
version: 1.0.0

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  html: ^0.15.2
  
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
