name: extension_dart_tools
description: Tools functions and extensions in dart
version: 1.3.0
repository: https://github.com/maxbritto/extension_dart_tools

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  html: ^0.15.2
  
dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4
